version: '2.1'
services:
  tor:
    image: tor
    container_name: tor
    build:
      context: tor/
      dockerfile: Dockerfile
    volumes:
      - etc_tor:/etc/tor
      - var_lib_tor:/var/lib/tor
    ports:
      - "9050:9050"
    

  lnd:
    image: lnd
    container_name: lnd
    build:
      context: lnd/
      dockerfile: Dockerfile
    volumes:
      - ./root_volume/:/root/.lnd
      - etc_tor:/etc/tor
      - var_lib_tor:/var/lib/tor
    ports:
      - "9735:9735"
      - "10009:10009"
    depends_on:
      tor:
        condition: service_healthy

  thunderhub:
    image: thunderhub
    container_name: thunderhub
    build:
      context: thunderhub/
      dockerfile: Dockerfile
    volumes:
      - ./root_volume:/root/.lnd
    ports:
      - "3000:3000"
    depends_on:
      tor:
        condition: service_healthy

volumes:
  etc_tor:
    driver: local

  var_lib_tor:
    driver: local
